### PR TITLE
Bump to version 1.18

### PR DESCRIPTION
**Pull request by JrCs**
Update functions to "update" init_mnt script and crontab file.
Fix invalid tests in init_nmt script.

Be careful to not change the sheebang from /bin/bash to /bin/sh !

### CODE REVIEW

**Comment by cptjhmiller** [comment]
Can't use bash so can't merge.

**Comment by JrCs** [comment]
Why you can't use bash ? 
It's in the original firmware and /bin/sh is a link to /bin/bash.

**Comment by cptjhmiller** [comment]
Does not work on the A100 series, the init file has to be compatible with those models as well.

**Comment by JrCs** [comment]
Commits update to not use /bin/bash and use /bin/sh instead

**Comment by cptjhmiller** [comment]
I will add this in the next few days, there is a new version of CSI coming so may wait until that is finished.
Thanks for the work you have done on this.

**Pull request merged**
